name: Lint and Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip" # Cache pip dependencies

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint --disable=W0511 shippy

      - name: Run MyPy
        run: |
          source venv/bin/activate
          mypy shippy

      - name: Run Black
        run: |
          source venv/bin/activate
          black --check shippy
